###############################################################################
# Copyright 2017-2018(c) The Ontario Institute for Cancer Research. All rights reserved.
################################################################################
# All Versions, Centralized for convenience.
# Cloudera
cloudera_major: 5
cloudera_version: "{{ cloudera_major }}.3.9"
cdh_version: "CDH{{ cloudera_major }}"
cdh_version_number: "{{ cloudera_version }}"
cm_version: "{{ cloudera_version }}"
cm_api_version: 9
openstack_security_groups: "Monitoring, jupyterhub"  

# Jupyterhub User setup 
jupyterhub_user: jupyterhub
jupyterhub_group: jupyterhub
jupyterhub_env: "jupyterhub"
jupyterhub_service: "{{ jupyterhub_user }}"
home: "/home/{{ jupyterhub_user }}"
jupyterhub_bin: "{{ home }}/bin"

# Jupyterhub Service configuration
jupyterhub_host: "jupyterhub.cancercollaboratory.org"
jupyterhub_port: 443 

# Location of Jupyterhub service inside Docker
service_dir: "/srv/jupyterhub/"

# Docker task currently symlinks these from the certbot files defined below
key_file: "~/secrets/ssl/privkey.pem"
cert_file: "~/secrets/ssl/cert.pem"

# Docker
docker_group: docker
oauthenticator_lib: "{{ home }}/lib/python3.5/site-packages/oauthenticator/"

# Google Client Id  
#oauth_client_id: ''      # set this from the secrets file 
#oauth_client_secret: ''  # set this from the secrets file 

# Daco
#daco_base_url: '' # set this in the secrets file
#daco_client_key: '' # set this in the secrets file
#daco_client_secret: '' # set this in the secrets file
#daco_token: '' # set this in the secrets file
#daco_token_secret: '' # set this in the secrets file

# Need to point external DNS to point this hostname 
# to the floating ip address of our host 
oauth_callback_url: "https://{{ jupyterhub_host }}:{{ jupyterhub_port }}/hub/oauth_callback" 

# SSL Client Certificate Information
certbot_cert: /etc/letsencrypt/live/jupyterhub.cancercollaboratory.org/cert.pem
certbot_key: /etc/letsencrypt/live/jupyterhub.cancercollaboratory.org/privkey.pem
certbot_email: kevin.hartmann@oicr.on.ca
