###############################################################################
# Copyright 2017-2018(c) The Ontario Institute for Cancer Research. All rights reserved.
################################################################################
# The port to run Jupyterhub on: the default is 443 (SSL)
jupyterhub_port: 443

# Base name for docker images, etc.
service_name: "jukebox"

# Use certbot to register and install SSL certificates for the site 
use_certbot: true
use_oauth: true
use_openstack: true
