# Copyright 2018(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Creates OpenStack VM instances for all our hosts 
  hosts: "{{ group }}"
  user: root
  gather_facts: no
  serial: 1
  vars_files:
    - "../vars/main.yml"
    - "{{ secrets_file }}"
  roles:
    - ../roles/teardown
