# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "2"

services:
  hub:
    build:
      context: hub
      dockerfile: Dockerfile.custom
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
        DEV_MODE: ${DEV_MODE}
    restart: always
    image: ${DOCKER_NOTEBOOK_IMAGE}
    container_name: ${CONTAINER_NAME}
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "data:${DATA_MOUNT_POINT}"
      - "./share:/srv/jupyterhub/share"
      - "~/secrets/ssl:/srv/jupyterhub/secrets"
    ports:
      - "${PORT}:${PORT}"
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: ${LOCAL_NOTEBOOK_IMAGE}
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      # Using this run command (optional)
      DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
      DEV_MODE: ${DEV_MODE}
      PORT: ${PORT}
    env_file:
      - ~/secrets/jupyterhub_oauth.env
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

volumes:
  data:
    external:
      name: ${DATA_VOLUME}

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
